const clubData = {
    'Texas Robotics': ['robotics', 'automation', 'engineering'],
    'Women in Engineering Program': ['women', 'engineering', 'support'],
    'UT Programming Club': ['programming', 'coding', 'software'],
    'Longhorn Entrepreneurship Agency': ['entrepreneurship', 'startup', 'business'],
    'AI Society at UT': ['artificial intelligence', 'machine learning', 'data science'],
   
    'Camp Kesem at the University of Texas at Austin': ['campus organization', 'charity', 'youth support'],
    '#DOTHATONETHING! Council': ['event planning', 'student engagement', 'leadership'],
    '(un)Jaded': ['mental health', 'support group', 'well-being'],
    '32º Figure Skating Club': ['sports', 'figure skating'],
    'ABC Residence Hall Council': ['housing', 'residence hall', 'student leadership'],
    'American Institute of Chemical Engineers': ['chemical engineering', 'engineering', 'science'],
    'American Journal of Criminal Law': ['law', 'criminal justice'],
    'American Library Association Student Chapter': ['library science', 'literature', 'research'],
    'American Marketing Association, UT Collegiate Chapter': ['marketing', 'business', 'advertising'],
    'American Medical Student Association - Pre-med': ['pre-med', 'medicine', 'healthcare'],
    'American Nuclear Society': ['nuclear science', 'engineering'],
    'American Red Cross Club at The University of Texas at Austin': ['volunteer', 'red cross', 'community service'],
    'American Rock Mechanics Association UT Student Chapter': ['geology', 'engineering', 'rock mechanics'],
    'American Society for Biochemistry and Molecular Biology Student Chapter at the University of Texas at Austin': ['biochemistry', 'biology', 'research'],
    'American Society for Microbiology at The University of Texas at Austin': ['microbiology', 'science', 'research'],
    'American Society of Civil Engineers': ['civil engineering', 'infrastructure', 'construction'],
    'American Society of Landscape Architects Student Chapter (ASLA)': ['landscape architecture', 'design'],
    'American Society of Mechanical Engineers': ['mechanical engineering', 'design', 'innovation'],
    'American Statistical Association at the University of Texas at Austin': ['statistics', 'data analysis'],
    'Animators Club': ['animation', 'art', 'media'],
    'Anime Club': ['anime', 'culture', 'entertainment'],
    'Anthropological Society at the University of Texas at Austin': ['anthropology', 'social sciences'],
    'Anthropology Graduate Student Association': ['graduate studies', 'anthropology'],
    'Apricity Magazine': ['journalism', 'magazine', 'writing'],
    'Arab Students Association': ['arab culture', 'community', 'students'],
    'Architectural Engineering Institute': ['architecture', 'engineering'],
    'Arnold Air Society': ['air force', 'aviation', 'leadership'],
    'Arrows of Christ': ['religion', 'spirituality', 'service'],
    'Art Education Workshops and Development': ['art education', 'workshops', 'creativity'],
    'Asian American Campus Ministry': ['religion', 'asian american', 'student ministry'],
    'Asian American Journalists Association at UT': ['journalism', 'media', 'asian american'],
    'Asian Business Students Association': ['business', 'asian american', 'networking'],
    'Asian Desi Pacific Islander American Collective': ['asian american', 'culture', 'inclusivity'],
    'Asian Pacific American Law Student Association': ['law', 'asian american', 'student association'],
    'Asian Pharmacy Students Association': ['pharmacy', 'asian american', 'healthcare'],
    'Asian/Asian American Faculty and Staff Association': ['faculty', 'staff', 'asian american'],
    'Assault & Flattery': ['comedy', 'performance', 'arts'],
    'Associated Students of Linguistics': ['linguistics', 'language', 'research'],
    'Association for Computing Machinery': ['computing', 'technology', 'coding'],
    'Association for Women in Mathematics - Texas Chapter': ['women', 'mathematics', 'STEM'],
    'Association of Black Computer Scientists': ['black students', 'technology', 'computing'],
    'Association of Latino Professionals For America': ['latino professionals', 'business', 'leadership'],
    'Association of Professionals in Student Affairs': ['student affairs', 'campus life'],
    'Association of Research Administrators': ['research', 'administration', 'academia'],
    'Astronomy Equity and Inclusion Discussion Group': ['astronomy', 'equity', 'inclusion'],
    'Astronomy Students Association': ['astronomy', 'students', 'science'],
    'Atidna at the University of Texas': ['jewish culture', 'students', 'community'],
    'ATX KDC': ['dance', 'community', 'culture'],
    'ATX Science Olympiad': ['science', 'competition', 'STEM'],
    'Austin AI Alignment': ['AI', 'alignment', 'research'],
    'Austin Alternative Protein Project': ['alternative protein', 'sustainability', 'science'],
    'Austin Bodybuilding': ['fitness', 'bodybuilding', 'health'],
    'Austin Chapter of SIAM': ['mathematics', 'research', 'students'],
    'Austin Chinese Campus Christian Fellowship': ['christianity', 'asian american', 'students'],
    'Austin Compassion Collective': ['volunteer', 'community', 'compassion'],
    'Austin Korean Presbyterian Church Psalm Young Adults': ['church', 'young adults', 'community'],
    'Austin STEM Buddies': ['STEM', 'mentorship', 'students'],
    'Austin Student Chapter of the Acoustical Society of America': ['acoustics', 'science', 'engineering'],
    'Austin Students for a Democratic Society': ['activism', 'students', 'democracy'],
    'Austin Sunshine Camps at The University of Texas at Austin': ['youth programs', 'outdoor activities', 'volunteer'],
    'Austin Swipe Out Hunger': ['hunger relief', 'community', 'students'],
    'Austin Texas Nursing Students\' Association': ['nursing', 'healthcare', 'students'],
    'AustinXChange': ['technology', 'entrepreneurship', 'business'],
    'AWAKE (Anointed Worship Awakes Koreans and Everyone)': ['worship', 'spirituality', 'community'],
    'B-Boy Session': ['dance', 'hip-hop', 'culture'],
    'Baháʼí Club at the University of Texas': ['religion', 'spirituality', 'community'],
    'Baines Report': ['journalism', 'media', 'writing'],
    'Balancing Aspects of Life through Activities, Normality and Community Effectively': ['wellness', 'life balance', 'student support'],
    'Bangladeshi Students Association at the University of Texas at Austin': ['bangladeshi culture', 'community'],
    'BAPS Campus Fellowship': ['religion', 'community', 'student fellowship'],
    'Baptist Student Ministry': ['religion', 'ministry', 'student engagement'],
    'Beauties and the Beat': ['dance', 'performance', 'arts'],
    'Because Inquiry Propels Our Curiosity': ['inquiry', 'learning', 'philosophy'],
    'Beekeeping Society': ['beekeeping', 'environment', 'sustainability'],
    'Bengali Students Association': ['bengali culture', 'students'],
    'Best Buddies': ['friendship', 'community', 'disabilities'],
    'Beta Beta Beta Biological Honor Society': ['biology', 'honor society', 'science'],
    'Beta Theta Pi at the University of Texas at Austin': ['fraternity', 'students', 'community'],
    'BeVocal: The Bystander Intervention Initiative of The University of Texas at Austin': ['intervention', 'social justice', 'bystander'],
    'Beyond Frames Productions': ['media', 'production', 'film'],
    'Bhakti Yoga Club': ['yoga', 'spirituality', 'well-being'],
    'Bilingual Education Student Organization': ['education', 'bilingual', 'students'],
    'Biomedical Engineering Graduate Student Society': ['biomedical engineering', 'graduate students'],
    'Biomedical Engineering Society': ['biomedical engineering', 'students', 'science'],
    'Biomedical Optics Graduates Organization': ['biomedical optics', 'science', 'research'],
    'Biomedical Outreach and Leadership Team': ['biomedical outreach', 'leadership', 'community'],
    'Black Ambitious Women Supporting Excellence': ['women', 'empowerment', 'support'],
    'Black Business Student Association': ['business', 'black students', 'networking'],
    'Black Graduate Student Association': ['black students', 'graduate students', 'community'],
    'Black Health Professions Organization- MAPS Chapter': ['health professions', 'black students', 'medical students'],
    'Black Homecoming Planning Committee': ['homecoming', 'event planning', 'student leadership'],
    'Black Muslims Alliance': ['muslim', 'community', 'diversity'],
    'Black Student Alliance': ['black students', 'leadership', 'community'],
    'Black Student Alliance\'s Freshman Action Team': ['black students', 'freshmen', 'leadership'],
    'Black Student Media Association': ['media', 'black students', 'journalism'],
    'Black Studies Graduate Student Organization': ['black studies', 'graduate students', 'academia'],
    'Black Women Wellness Organization': ['women', 'wellness', 'empowerment'],
    'Blanton Museum of Art': ['art', 'museum', 'culture'],
    'Board Fellows': ['student leadership', 'nonprofit', 'board service'],
    'Board of Advocates - Law School': ['law', 'advocacy', 'students'],
    'Brackenridge, Roberts, & Prather Residence Hall Council': ['residence hall', 'student leadership'],
    'BRASA at University of Texas-Austin': ['brazilian students', 'culture', 'community'],
    'Brazilian Jiu Jitsu at the University of Texas': ['martial arts', 'jiu jitsu', 'fitness'],
    'Bridges International - Texas Chapter': ['international', 'students', 'community'],
    'BridgeTexas': ['bridge', 'students', 'communication'],
    'Bright Stars of Texas': ['leadership', 'students', 'community service'],
    'Broccoli Project': ['sustainability', 'health', 'environment'],
    'Buddha\'s Light International Association- Austin Young Adult Division- Longhorn Chapter': ['buddhism', 'spirituality', 'community'],
    'Business Analytics Association': ['business', 'analytics', 'data science'],
    'Business Ethics Team': ['business ethics', 'students', 'leadership'],
    'Caduceus': ['healthcare', 'medicine', 'students'],
    'Calisthenics Connect': ['fitness', 'exercise', 'community'],
    'Campus Cat Coalition': ['animals', 'student organization', 'community service'],
    'Campus Elections': ['student elections', 'leadership', 'campaigns'],
    'Campus Environmental Center': ['environment', 'sustainability', 'student action'],
    'Campus Events + Entertainment': ['events', 'entertainment', 'students'],
    'Careyaya at The University of Texas at Austin': ['social welfare', 'community service'],
    'Cassidy Joined for Hope at the University of Texas': ['mental health', 'support', 'students'],
    'Catholic Law Student Society': ['law', 'catholic', 'students'],
    'Celebration Young Adults at the University of Texas at Austin': ['spirituality', 'young adults', 'community'],
    'Cellists at Texas': ['music', 'performance', 'students'],
    'Center for Asian American Studies': ['asian american', 'education', 'community'],
    'Center Space Project': ['community', 'outreach', 'student engagement'],
    'Central American Student Association': ['Central American', 'Cultural', 'Community', 'Latino'],
    'Central Texas Model United Nations': ['MUN', 'Debate', 'Global Affairs', 'Model United Nations'],
    'Chabad Jewish Student Organization': ['Jewish', 'Community', 'Cultural', 'Faith'],
    'Change1': ['Social Justice', 'Advocacy', 'Community', 'Awareness'],
    'Changing Health, Attitudes and Actions to Recreate Girls': ['Health', 'Empowerment', 'Youth', 'Community'],
    'Chess Club': ['Chess', 'Strategy', 'Board Games', 'Club'],
    'Chi Beta Delta Service Sorority': ['Service', 'Sorority', 'Community', 'Philanthropy'],
    'Chi Kappa Phi Service Society': ['Service', 'Community', 'Philanthropy', 'Greek'],
    'Chi Omega Sorority': ['Sorority', 'Greek', 'Philanthropy', 'Sisterhood'],
    'Chicano/Hispanic/Latino Law Students\' Association': ['Chicano', 'Hispanic', 'Latino', 'Law', 'Student Organization'],
    'Children\'s Oral Health Advocacy Project': ['Health', 'Children', 'Advocacy', 'Oral Health'],
    'Chinese Orchestra at UT Austin': ['Chinese', 'Orchestra', 'Music', 'Cultural'],
    'Chinese Student Association': ['Chinese', 'Culture', 'Community', 'Student Organization'],
    'Chinese Students and Scholars Association': ['Chinese', 'Scholars', 'Culture', 'Student Organization'],
    'Christian Business Student Council': ['Christian', 'Business', 'Leadership', 'Student Organization'],
    'Christian Legal Society': ['Christian', 'Law', 'Faith', 'Legal'],
    'Christian Students on Campus': ['Christian', 'Faith', 'Campus', 'Community'],
    'CHYK West at the University of Texas at Austin': ['Christian', 'Youth', 'Community', 'Faith'],
    'Circle K International': ['Service', 'Leadership', 'Community', 'International'],
    'CliftonStrengths for Students': ['Strengths', 'Personal Development', 'Leadership', 'Student Organization'],
    'ClockTower Cultural Productions': ['Cultural', 'Music', 'Events', 'Art'],
    'Club Golf': ['Golf', 'Sports', 'Club', 'Recreation'],
    'Club Tennis': ['Tennis', 'Sports', 'Club', 'Recreation'],
    'Collaboration for Undoing Racism in Environmental Sciences': ['Environmental Science', 'Racism', 'Diversity', 'Social Justice'],
    'Collaborative Artists': ['Art', 'Community', 'Artists', 'Collaboration'],
    'College of Education Career Service': ['Education', 'Career', 'Service', 'Student Organization'],
    'College of Fine Arts': ['Art', 'Education', 'Fine Arts', 'Student Organization'],
    'College of Natural Sciences Peer Leader Academy': ['Natural Sciences', 'Leadership', 'Academy', 'Peer Mentorship'],
    'College of Natural Sciences Student Life': ['Natural Sciences', 'Student Life', 'Community', 'Support'],
    'College Republicans at Texas': ['Republicans', 'Politics', 'Student Organization', 'Leadership'],
    'ColorStack at UT Austin': ['Tech', 'Diversity', 'Networking', 'Professional Development'],
    'Communication Council': ['Communication', 'Leadership', 'Student Organization', 'Academics'],
    'Community Engagement and Advocacy Agency of Student Government': ['Advocacy', 'Community', 'Student Government', 'Engagement'],
    'Consult Your Community- Texas Chapter': ['Consulting', 'Community', 'Texas', 'Service'],
    'Crafter\'s Circle': ['Crafts', 'Hobbies', 'Community', 'Art'],
    'Creative Art Collective': ['Art', 'Creativity', 'Community', 'Collaboration'],
    'Creative Writers at UT': ['Writing', 'Creative', 'Community', 'Literature'],
    'Creative Writing MFA Student Collective': ['Creative Writing', 'MFA', 'Literature', 'Community'],
    'Central American Student Association': ['culture', 'students', 'advocacy'],
    'Central Texas Model United Nations': ['international', 'debate', 'students'],
    'Chabad Jewish Student Organization': ['religion', 'community', 'students'],
    'Change1': ['social', 'advocacy', 'students'],
    'Changing Health, Attitudes and Actions to Recreate Girls': ['health', 'advocacy', 'students'],
    'Chess Club': ['games', 'students', 'strategy'],
    'Chi Beta Delta Service Sorority': ['service', 'sorority', 'community'],
    'Chi Kappa Phi Service Society': ['service', 'society', 'students'],
    'Chi Omega Sorority': ['sorority', 'sisterhood', 'community'],
    'Chicano/Hispanic/Latino Law Students\' Association': ['law', 'advocacy', 'students'],
    'Children\'s Oral Health Advocacy Project': ['health', 'advocacy', 'community'],
    'Chinese Orchestra at UT Austin': ['music', 'performance', 'students'],
    'Chinese Student Association': ['culture', 'students', 'community'],
    'Chinese Students and Scholars Association': ['culture', 'students', 'community'],
    'Christian Business Student Council': ['business', 'religion', 'students'],
    'Christian Legal Society': ['law', 'religion', 'students'],
    'Christian Students on Campus': ['religion', 'students', 'community'],
    'CHYK West at the University of Texas at Austin': ['religion', 'community', 'students'],
    'Circle K International': ['service', 'community', 'students'],
    'CliftonStrengths for Students': ['personal development', 'students', 'leadership'],
    'ClockTower Cultural Productions': ['arts', 'culture', 'students'],
    'Club Golf': ['sports', 'students', 'recreation'],
    'Club Tennis': ['sports', 'students', 'recreation'],
    'Collaboration for Undoing Racism in Environmental Sciences': ['advocacy', 'environment', 'students'],
    'Collaborative Artists': ['arts', 'collaboration', 'students'],
    'College of Education Career Service': ['education', 'career', 'students'],
    'College of Fine Arts': ['arts', 'education', 'students'],
    'College of Natural Sciences Peer Leader Academy': ['education', 'science', 'students'],
    'College of Natural Sciences Student Life': ['education', 'students', 'engagement'],
    'College Republicans at Texas': ['politics', 'students', 'advocacy'],
    'ColorStack at UT Austin': ['technology', 'diversity', 'students'],
    'Communication Council': ['communication', 'students', 'leadership'],
    'Community Engagement and Advocacy Agency of Student Government': ['community', 'advocacy', 'students'],
    'Consult Your Community- Texas Chapter': ['consulting', 'community', 'students'],
    'Crafter\'s Circle': ['crafts', 'students', 'community'],
    'Creative Art Collective': ['arts', 'collaboration', 'students'],
    'Creative Writers at UT': ['writing', 'arts', 'students'],
    'Creative Writing MFA Student Collective': ['writing', 'arts', 'students'],
    'Creekside Residence Hall Council': ['student life', 'residence', 'leadership'],
    'Criminal Law Association': ['law', 'students', 'advocacy'],
    'Crochet 4 a Cause': ['crafts', 'community', 'service'],
    'Cross Training Club at the University of Texas': ['fitness', 'sports', 'students'],
    'Crossroads': ['religion', 'community', 'students'],
    'Cybersecurity Society at The University of Texas at Austin': ['technology', 'security', 'students'],
    'Dead Improv Society': ['comedy', 'performance', 'students'],
    'Deaf Culture Alliance at the University of Texas at Austin': ['culture', 'advocacy', 'students'],
    'Dean\'s Scholars Student Association': ['academics', 'students', 'leadership'],
    'Dean\'s Squad': ['academics', 'students', 'community'],
    'Dell Medical School - Student Affairs': ['health', 'students', 'medical'],
    'Delta Delta Delta': ['sorority', 'sisterhood', 'community'],
    'Delta Epsilon Mu-Sigma Chapter': ['sorority', 'service', 'community'],
    'Delta Epsilon Psi Fraternity, Inc': ['fraternity', 'service', 'community'],
    'Delta Gamma': ['sorority', 'sisterhood', 'community'],
    'Delta Phi Omega Sorority, Incorporated': ['sorority', 'diversity', 'community'],
    'Delta Sigma Pi': ['business', 'students', 'networking'],
    'Delta Tau Delta': ['fraternity', 'sisterhood', 'community'],
    'Delta Theta Mu': ['sorority', 'students', 'service'],
    'Delta Upsilon': ['fraternity', 'leadership', 'community'],
    'Department of Biomedical Engineering': ['engineering', 'biomedical', 'students'],
    'Department of Civil, Architectural and Environmental Engineering': ['engineering', 'architecture', 'students'],
    'Desi Students of Texas': ['culture', 'students', 'community'],
    'Design in Health': ['design', 'health', 'students'],
    'Dialogue Student Association': ['communication', 'students', 'advocacy'],
    'Dinner with 16 Longhorns': ['networking', 'students', 'community'],
    'Disabilities Inclusion Agency of Student Government': ['advocacy', 'students', 'inclusion'],
    'Disability Advocacy Student Coalition': ['advocacy', 'students', 'disability'],
    'Disability and Access': ['advocacy', 'students', 'accessibility'],
    'Disability Cultural Center': ['culture', 'advocacy', 'students'],
    'Discovery Scholars Program': ['academics', 'research', 'students'],
    'Diversity in Advertising & PR': ['advertising', 'diversity', 'students'],
    'Division of Student Affairs': ['students', 'support', 'community'],
    'DKA Professional Cinematic Society': ['cinema', 'professional development', 'students'],
    'DoS Graduate Assistant Supervisors': ['students', 'leadership', 'administration'],
    'DoS Graduate Assistants': ['students', 'leadership', 'administration'],
    'Dream Corps at the University of Texas at Austin': ['advocacy', 'social change', 'students'],
    'Drift Magazine ATX': ['media', 'arts', 'students'],
    'Duren and Whitis Court Residence Hall Council': ['student life', 'residence', 'leadership'],
    'e-NABLE at UT Austin': ['technology', 'volunteer', 'engineering'],
    'E3W': ['environment', 'students', 'advocacy'],
    'EcoCAR at UT': ['environment', 'engineering', 'students'],
    'Education for All': ['education', 'advocacy', 'students'],
    'EERI (Earthquake Engineering Research Institute)': ['engineering', 'research', 'students'],
    'Effective Altruism at University of Texas at Austin': ['advocacy', 'philanthropy', 'students'],
    'Election Supervisory Board': ['government', 'students', 'leadership'],
    'Electrical Computer Engineering and Business Association': ['engineering', 'business', 'students'],
    'Electronic Game Developers Society': ['technology', 'gaming', 'students'],
    'Elevate Student Fellowship': ['leadership', 'students', 'mentorship'],
    'ELPSA Student Organization': ['education', 'students', 'community'],
    'Emancipet on Campus': ['health', 'community', 'volunteer'],
    'Emergency Contraception for Every Campus': ['health', 'advocacy', 'students'],
    'Empowered Education': ['education', 'students', 'advocacy'],
    'Engineering and Computational Learning of Artificial Intelligence in Robotics': ['engineering', 'technology', 'students'],
    'Engineering Chamber Orchestra': ['music', 'performance', 'students'],
    'Engineering Student Life': ['engineering', 'students', 'community'],
    'Engineers for a Sustainable World': ['engineering', 'sustainability', 'students'],
    'Entrepreneurship through Acquisition Club': ['business', 'entrepreneurship', 'students'],
    'Environmental Justice and Eco-Therapy Student Organization': ['environment', 'advocacy', 'students'],
    'Environmental Law Society': ['law', 'environment', 'students'],
    'Epic Movement': ['religion', 'students', 'community'],
    'Episcopal Campus Ministry': ['religion', 'students', 'community'],
    'Epsilon Beta Chapter of Delta Sigma Theta Sorority Inc.': ['sorority', 'community', 'students'],
    'Epsilon Nu Tau- Phi Collegiate Chapter': ['fraternity', 'community', 'students'],
    'Equal Opportunity in Engineering Program': ['engineering', 'diversity', 'students'],
    'Equity, Visibility, and Inclusion for Longhornz': ['advocacy', 'students', 'diversity'],
    'Eta Kappa Nu: Electrical Engineering': ['engineering', 'students', 'honor society'],
    'Eta Sigma Phi': ['honor society', 'students', 'classics'],
    'Every Nation Campus': ['religion', 'students', 'community'],
    'Experimental Division Combat Robotics Club': ['engineering', 'robots', 'students'],
    'Feminist Action Project': ['feminism', 'advocacy', 'students'],
    'Filipino Students Association': ['culture', 'students', 'community'],
    'Financial Literacy Club @ UT Austin': ['finance', 'students', 'education'],
    'Fine Arts Council': ['arts', 'students', 'leadership'],
    'First-Year & Transfer-Year Experience': ['students', 'transition', 'support'],
    'First-Year Leadership Organization of Student Government': ['leadership', 'students', 'government'],
    'Food Security Agency of Student Government': ['advocacy', 'students', 'food security'],
    'Foot in the Door Theatre': ['arts', 'performance', 'students'],
    'Forever Texas': ['spirit', 'students', 'community'],
    'Freshman Launch': ['students', 'orientation', 'leadership'],
    'Friar Society': ['service', 'community', 'students'],
    'Friends of MSF at UT Austin': ['health', 'philanthropy', 'students'],
    'Front \'N Center': ['arts', 'students', 'performance'],
    'Fuse A Cappella': ['music', 'performance', 'students'],
    'Future Doctors of America': ['medicine', 'students', 'pre-health'],
    'Gamma Beta Fraternity, Inc.': ['fraternity', 'service', 'community'],
    'Gamma Iota Sigma @ UT Austin': ['business', 'students', 'networking'],
    'Gamma Rho Lambda': ['sorority', 'community', 'students'],
    'Gamma Sigma Alpha': ['honor society', 'students', 'academics'],
    'Gappa Book Club': ['literature', 'community', 'students'],
    'Gender and Sexuality Center at UT Austin': ['advocacy', 'LGBTQ+', 'students'],
    'General Assembly': ['advocacy', 'students', 'engagement'],
    'Germanic Languages & Literatures at the University of Texas at Austin': ['language', 'culture', 'students'],
    'Global Connections': ['culture', 'students', 'international'],
    'Global Peace and Justice Project': ['advocacy', 'students', 'social change'],
    'Global Medical Brigades at UT Austin': ['health', 'volunteer', 'students'],
    'Global South Scholars': ['education', 'diversity', 'students'],
    'Gnome Club': ['computers', 'community', 'technology'],
    'Golden Key International Honour Society': ['honor society', 'students', 'academics'],
    'Greek Life': ['community', 'students', 'sorority'],
    'Green Business Initiative': ['business', 'environment', 'students'],
    'Green Films': ['environment', 'media', 'students'],
    'Greater Austin Community Band': ['music', 'community', 'performance'],
    'Graduate Business Association': ['business', 'students', 'networking'],
    'Graduate Economic Society': ['economics', 'students', 'networking'],
    'Graduate Engineering Council': ['engineering', 'students', 'leadership'],
    'Graduate Student Association': ['students', 'support', 'leadership'],
    'Graduate Students in History': ['students', 'history', 'academic'],
    'Graduate Students for a Sustainable Campus': ['environment', 'students', 'advocacy'],
    'Guitar Club': ['music', 'students', 'recreation'],
    'HackTX': ['technology', 'students', 'hackathon'],
    'Hacks for Humanity': ['technology', 'social good', 'students'],
    'Haitian Student Association': ['culture', 'students', 'community'],
    'Handmade at UT': ['crafts', 'students', 'community'],
    'Harrison Love': ['community', 'social good', 'students'],
    'Hatchers': ['organization', 'support', 'volunteer'],
    'Health at Texas': ['health', 'students', 'community'],
    'Health Council': ['health', 'students', 'advocacy'],
    'Hindu Students Association': ['culture', 'students', 'religion'],
    'Historical Association of the University of Texas at Austin': ['history', 'students', 'academic'],
    'Hispanic Business Students Association': ['business', 'students', 'diversity'],
    'Hispanic Faculty & Staff Association': ['community', 'students', 'advocacy'],
    'Hispanic Graduate Student Association': ['graduate', 'community', 'advocacy'],
    'Hispanic/Latino Association of University Students': ['students', 'community', 'culture'],
    'Hispanic Association of Computer Scientists': ['technology', 'students', 'diversity'],
    'Hispanic Association of Pharmacists': ['health', 'students', 'diversity'],
    'Hispanic Business Student Association': ['business', 'students', 'diversity'],
    'HISPANIC FACULTY STAFF ASSOCIATION (HFSA)': ['community', 'students', 'advocacy'],
    'Hispanic Nursing Student Association': ['health', 'students', 'diversity'],
    'Hispanic Pre-Dental Society': ['health', 'students', 'diversity'],
    'Hispanic Public Relations Student Association': ['public relations', 'students', 'diversity'],
    'Hong Kong Students Association': ['culture', 'students', 'community'],
    'Honors Business Association': ['business', 'students', 'academics'],
    'Hook \'Em Arts': ['arts', 'students', 'community'],
    'Hook the Vote Agency of Student Government': ['advocacy', 'students', 'engagement'],
    'Hook\'d Magazine': ['media', 'students', 'publication'],
    'Hooked Bhangra': ['culture', 'students', 'performance'],
    'Hooked On Books': ['literature', 'students', 'community'],
    'Hooked On Skin Care': ['health', 'students', 'wellness'],
    'Hopelessly Yellow Texas': ['community', 'students', 'support'],
    'Horns for Life': ['community', 'students', 'support'],
    'Horns Lens - Photography Org': ['photography', 'students', 'arts'],
    'Horns Sports Debate': ['sports', 'students', 'debate'],
    'HOSA- Future Health Professionals': ['health', 'students', 'professional'],
    'Hum A Cappella': ['music', 'students', 'performance'],
    'Human Dimensions of Organizations Undergraduate Organization': ['organization', 'students', 'leadership'],
    'ICMA at the University of Texas': ['business', 'students', 'networking'],
    'IEEE Power and Energy Society': ['engineering', 'students', 'networking'],
    'IEEE Robotics and Automation Society': ['engineering', 'students', 'technology'],
    'If/When/How Texas Law': ['law', 'students', 'advocacy'],
    'IFORTY Administrative Professional Network': ['professionals', 'students', 'networking'],
    'IGNITE National at UT Austin': ['leadership', 'students', 'empowerment'],
    'Ignite Texas': ['advocacy', 'students', 'empowerment'],
    'In Between the Lines': ['literature', 'students', 'community'],
    'Indian Cultural Association': ['culture', 'students', 'community'],
    'Indian Orthodox Campus Ministry': ['religion', 'students', 'community'],
    'Indian Students Association': ['culture', 'students', 'community'],
    'Indigo Collective@UT': ['arts', 'students', 'culture'],
    'Indonesian Student Association (PERMIAS)': ['culture', 'students', 'community'],
    'Informatics Undergraduate Student Council': ['technology', 'students', 'leadership'],
    'Information and Systems Security Society (ISSS)': ['technology', 'students', 'security'],
    'INFORMS Student Chapter at The University of Texas at Austin': ['business', 'students', 'networking'],
    'Institute of Electrical & Electronics Engineers': ['engineering', 'students', 'networking'],
    'Intellectual Property Law Society': ['law', 'students', 'advocacy'],
    'Interdisciplinary Life Sciences Graduate Student Assembly': ['life sciences', 'students', 'graduate'],
    'Interfraternity Council': ['fraternity', 'students', 'community'],
    'International Affairs Society': ['international', 'students', 'advocacy'],
    'International Engineering Education (IEE)': ['engineering', 'students', 'international'],
    'International Graduate Student Ministry - at Austin': ['religion', 'students', 'support'],
    'International Relations and Global Studies Council': ['global studies', 'students', 'networking'],
    'International Student Mentorship Program at UT': ['international', 'students', 'support'],
    'International Undergraduate Student Ministry-Austin': ['religion', 'students', 'support'],
    'Interpreters in Healthcare': ['health', 'students', 'volunteer'],
    'InterVarsity Christian Fellowship': ['religion', 'students', 'community'],
    'Iranian Students Academic and Cultural Organization': ['culture', 'students', 'community'],
    'Ismaili Muslim Students Association': ['religion', 'students', 'culture'],
    'ISPOR': ['health', 'students', 'research'],
    'J. Reuben Clark Law Society': ['law', 'students', 'networking'],
    'Jackson School of Geosciences': ['geosciences', 'students', 'academic'],
    'Jain Students Association': ['religion', 'students', 'culture'],
    'Japanese Association': ['culture', 'students', 'community'],
    'Jeeyar International Youth Association': ['religion', 'students', 'youth'],
    'Jester East Residence Hall Council': ['residence', 'students', 'leadership'],
    'Jester West Residence Hall Council': ['residence', 'students', 'leadership'],
    'Jewish Legal Society': ['law', 'students', 'community'],
    'Journal of Law and Technology at Texas': ['law', 'students', 'publication'],
    'Journalism Graduate Student Council': ['journalism', 'graduate', 'students'],
    'K-pop Beat': ['music', 'students', 'culture'],
    'Kappa Alpha Psi Fraternity, Inc.': ['fraternity', 'students', 'community'],
    'Kappa Alpha Theta': ['sorority', 'students', 'community'],
    'Kappa Delta': ['sorority', 'students', 'community'],
    'Kappa Delta Chi Sorority, Incorporated': ['sorority', 'students', 'community'],
    'Kappa Epsilon - Pharmacy': ['pharmacy', 'students', 'health'],
    'Kappa Kappa Psi': ['music', 'students', 'fraternity'],
    'Kappa Phi Gamma Sorority, Inc.': ['sorority', 'students', 'community'],
    'Kappa Phi Lambda Sorority, Inc.': ['sorority', 'students', 'community'],
    'Kappa Rho Pre-Medical Honors Sorority': ['pre-med', 'students', 'honors'],
    'Kappa Sigma Fraternity': ['fraternity', 'students', 'community'],
    'Kappa Theta Pi at the University of Texas at Austin': ['technology', 'students', 'honors'],
    'Kendo Association at The University of Texas at Austin': ['culture', 'students', 'martial arts'],
    'Kendra Scott Women\'s Entrepreneurial Leadership Institute Student Board': ['entrepreneurship', 'students', 'leadership'],
    'Kinesiology Club': ['health', 'students', 'sports'],
    'Kinsolving Residence Hall Council': ['residence', 'students', 'leadership'],
    'Koinonia Christian Fellowship': ['religion', 'students', 'community'],
    'Kontrol Crew Texas': ['dance', 'students', 'performance'],
    'Korean American Student Association at Austin': ['culture', 'students', 'community'],
    'Korean Music Association': ['music', 'students', 'culture'],
    'KVRX Student Radio': ['media', 'students', 'radio'],
    'La Fe (Latino Fellowship)': ['religion', 'students', 'community'],
    'Lambda Chi Alpha Fraternity': ['fraternity', 'students', 'community'],
    'Lambda Phi Epsilon Fraternity, Inc.': ['fraternity', 'students', 'community'],
    'Lambda Theta Alpha Latin Sorority Incorporated': ['sorority', 'students', 'community'],
    'Lang Stuttering Institute Student Leadership Organization': ['health', 'students', 'research'],
    'Last Writers at the University of Texas at Austin': ['writing', 'students', 'community'],
    'Latin Economics and Business Association': ['business', 'students', 'networking'],
    'Latina/x and Indigenous Leadership Institute': ['leadership', 'students', 'diversity'],
    'Latinx Community Affairs': ['community', 'students', 'advocacy'],
    'Latinx Graduate Student Association at UT Austin': ['graduate', 'students', 'community'],
    'Latinx Health Professions Organization': ['health', 'students', 'community'],
    'Latinx Students & Scholars Network': ['students', 'diversity', 'community'],
    'Latinx Theatre Initiative at UT Austin': ['theater', 'students', 'culture'],
    'Law and Society Reading Club': ['law', 'students', 'community'],
    'Law Students For Black Lives': ['law', 'students', 'advocacy'],
    'Law Students for Life at The University of Texas at Austin': ['law', 'students', 'advocacy'],
    'LC Living Hope Ministry': ['religion', 'students', 'community'],
    'Lebanese Cultural Organization': ['culture', 'students', 'community'],
    'Legal and Social Work Alliance Journal': ['law', 'students', 'publication'],
    'Liberal Arts Council': ['liberal arts', 'students', 'leadership'],
    'Liberal Arts Honors Student Council': ['liberal arts', 'students', 'leadership'],
    'Liberal Arts Pre-Med Society': ['pre-med', 'students', 'academic'],
    'Lifelong Learning with Friends at the University of Texas at Austin': ['education', 'students', 'community'],
    'Lions Club at the University of Texas at Austin': ['service', 'students', 'community'],
    'Little Health Heroes': ['health', 'students', 'volunteer'],
    'Live Design Graduates': ['design', 'students', 'graduate'],
    'Lone Star Student Fellowship': ['faith', 'students', 'community'],
    'Longhorn Agave Association': ['students', 'culture', 'community'],
    'Longhorn Airmen': ['aviation', 'students', 'club'],
    'Longhorn Art Therapy Club': ['art', 'students', 'therapy'],
    'Longhorn Athletic Training Student Association': ['health', 'students', 'athletics'],
    'Longhorn Bakers': ['baking', 'students', 'community'],
    'Longhorn Band Student Association': ['music', 'students', 'performance'],
    'Longhorn Baseball Club': ['sports', 'students', 'club'],
    'Longhorn Beach Volleyball': ['sports', 'students', 'recreation'],
    'Longhorn Bitcoin Club': ['cryptocurrency', 'students', 'technology'],
    'Longhorn Bridge Club': ['students', 'games', 'recreation'],
    'Longhorn Car Club': ['automotive', 'students', 'recreation'],
    'Longhorn Catholic Council': ['religion', 'students', 'community'],
    'Longhorn Center for Academic Excellence': ['academic', 'students', 'support'],
    'Longhorn Chi Alpha Christian Fellowship': ['religion', 'students', 'community'],
    'Longhorn Comic Books': ['comics', 'students', 'club'],
    'Longhorn Cubing Club': ['puzzles', 'students', 'recreation'],
     "Longhorn Dance Club": ["dance", "students", "performance"],
  "Longhorn Digital Marketing": ["marketing", "students", "digital"],
  "Longhorn Don't Litter": ["environment", "students", "cleanup"],
  "Longhorn EMS Agency of Student Government": ["healthcare", "students", "emergency"],
  "Longhorn Energy Club": ["energy", "students", "sustainability"],
  "Longhorn Esports": ["gaming", "students", "competition"],
  "Longhorn for Harm Reduction": ["healthcare", "students", "wellness"],
  "Longhorn Gaming": ["gaming", "students", "recreation"],
  "Longhorn GeoGuessr": ["gaming", "students", "geography"],
  "Longhorn HeARTists": ["art", "students", "creativity"],
  "Longhorn Hellraisers": ["gaming", "students", "competition"],
  "Longhorn International Justice Mission": ["justice", "students", "global"],
  "Longhorn Investment Team": ["finance", "students", "investing"],
  "Longhorn Ladies in Action": ["women", "students", "leadership"],
  "Longhorn Legal Coalition": ["law", "students", "advocacy"],
  "Longhorn Legislative Aide Agency of Student Government": ["politics", "students", "government"],
  "Longhorn Lemons Racing - Orange Dames": ["racing", "students", "competition"],
  "Longhorn Link Program": ["students", "mentorship", "leadership"],
  "Longhorn LoveWorld": ["religion", "students", "community"],
  "Longhorn Macro Investors": ["finance", "students", "investing"],
  "Longhorn Marketing Consulting Group": ["marketing", "students", "consulting"],
  "Longhorn Megagames": ["gaming", "students", "recreation"],
  "Longhorn Music Business Club": ["music", "students", "business"],
  "Longhorn Mycological Society": ["science", "students", "mycology"],
  "Longhorn Neurotech": ["technology", "students", "neuroscience"],
  "Longhorn Outdoor Club": ["outdoors", "students", "recreation"],
  "Longhorn Philosophy, Politics/Ethics, and Economics Association": ["philosophy", "politics", "ethics", "economics"],
  "Longhorn Pokemon TCG": ["gaming", "students", "pokemon"],
  "Longhorn Powerlifting": ["fitness", "students", "powerlifting"],
  "Longhorn Puzzle Club": ["puzzles", "students", "recreation"],
  "Longhorn Quidditch": ["sports", "students", "competition"],
  "Longhorn Racing": ["racing", "students", "competition"],
  "Longhorn Riichi": ["gaming", "students", "competition"],
  "Longhorn Scholars Program": ["students", "academic", "leadership"],
  "Longhorn Singers": ["music", "students", "performance"],
  "Longhorn Social Dance": ["dance", "students", "social"],
  "Longhorn Songwriters": ["music", "students", "creativity"],
  "Longhorn Squash Club": ["sports", "students", "recreation"],
  "Longhorn Students For Israel": ["students", "culture", "community"],
  "Longhorn Swim Club": ["sports", "students", "swimming"],
  "Longhorn Table Tennis": ["sports", "students", "recreation"],
  "Longhorn Toy Factory": ["creativity", "students", "arts"],
  "Longhorn Urbanists": ["urbanism", "students", "community"],
  "Longhorn Voices Book Club": ["reading", "students", "books"],
  "Longhorn Westies": ["dance", "students", "performance"],
  "Longhorn Wrestling": ["sports", "students", "competition"],
  "Longhorns For Christ": ["religion", "students", "community"],
  "LSC at UT": ["leadership", "students", "community"],
  "Lutheran Campus Ministry": ["religion", "students", "faith"],
  "Machine Learning and Data Science": ["technology", "students", "machine learning"],
  "Management Information Systems Association": ["business", "students", "technology"],
  "Marine Science Institute Graduate Student Association": ["science", "students", "marine"],
  "Math Club": ["math", "students", "academic"],
  "Mathematics Graduate Representative Committee": ["math", "students", "academic"],
  "MBA Soccer Club": ["sports", "students", "soccer"],
  "Mechanical Engineering Graduate Student Board": ["engineering", "students", "mechanical"],
  "MEDLIFE at The University of Texas at Austin": ["healthcare", "students", "volunteering"],
  "MEDSIM": ["medicine", "students", "simulation"],
  "Mending Medical Minds": ["healthcare", "students", "volunteering"],
  "Mens Basketball Club": ["sports", "students", "basketball"],
  "Mental Health Agency of Student Government": ["health", "students", "mental health"],
  "Meow Mates": ["animals", "students", "pets"],
  "Michael T. Woodward Special Warfare Club": ["military", "students", "special forces"],  
  "Longhorn Dance Club": ["dance", "students", "performance"],
  "Longhorn Digital Marketing": ["marketing", "students", "digital"],
  "Longhorn Don't Litter": ["environment", "students", "cleanup"],
  "Longhorn EMS Agency of Student Government": ["healthcare", "students", "emergency"],
  "Longhorn Energy Club": ["energy", "students", "sustainability"],
  "Longhorn Esports": ["gaming", "students", "competition"],
  "Longhorn for Harm Reduction": ["healthcare", "students", "wellness"],
  "Longhorn Gaming": ["gaming", "students", "recreation"],
  "Longhorn GeoGuessr": ["gaming", "students", "geography"],
  "Longhorn HeARTists": ["art", "students", "creativity"],
  "Longhorn Hellraisers": ["gaming", "students", "competition"],
  "Longhorn International Justice Mission": ["justice", "students", "global"],
  "Longhorn Investment Team": ["finance", "students", "investing"],
  "Longhorn Ladies in Action": ["women", "students", "leadership"],
  "Longhorn Legal Coalition": ["law", "students", "advocacy"],
  "Longhorn Legislative Aide Agency of Student Government": ["politics", "students", "government"],
  "Longhorn Lemons Racing - Orange Dames": ["racing", "students", "competition"],
  "Longhorn Link Program": ["students", "mentorship", "leadership"],
  "Longhorn LoveWorld": ["religion", "students", "community"],
  "Longhorn Macro Investors": ["finance", "students", "investing"],
  "Longhorn Marketing Consulting Group": ["marketing", "students", "consulting"],
  "Longhorn Megagames": ["gaming", "students", "recreation"],
  "Longhorn Music Business Club": ["music", "students", "business"],
  "Longhorn Mycological Society": ["science", "students", "mycology"],
  "Longhorn Neurotech": ["technology", "students", "neuroscience"],
  "Longhorn Outdoor Club": ["outdoors", "students", "recreation"],
  "Longhorn Philosophy, Politics/Ethics, and Economics Association": ["philosophy", "politics", "ethics", "economics"],
  "Longhorn Pokemon TCG": ["gaming", "students", "pokemon"],
  "Longhorn Powerlifting": ["fitness", "students", "powerlifting"],
  "Longhorn Puzzle Club": ["puzzles", "students", "recreation"],
  "Longhorn Quidditch": ["sports", "students", "competition"],
  "Longhorn Racing": ["racing", "students", "competition"],
  "Longhorn Riichi": ["gaming", "students", "competition"],
  "Longhorn Scholars Program": ["students", "academic", "leadership"],
  "Longhorn Singers": ["music", "students", "performance"],
  "Longhorn Social Dance": ["dance", "students", "social"],
  "Longhorn Songwriters": ["music", "students", "creativity"],
  "Longhorn Squash Club": ["sports", "students", "recreation"],
  "Longhorn Students For Israel": ["students", "culture", "community"],
  "Longhorn Swim Club": ["sports", "students", "swimming"],
  "Longhorn Table Tennis": ["sports", "students", "recreation"],
  "Longhorn Toy Factory": ["creativity", "students", "arts"],
  "Longhorn Urbanists": ["urbanism", "students", "community"],
  "Longhorn Voices Book Club": ["reading", "students", "books"],
  "Longhorn Westies": ["dance", "students", "performance"],
  "Longhorn Wrestling": ["sports", "students", "competition"],
  "Longhorns For Christ": ["religion", "students", "community"],
  "LSC at UT": ["leadership", "students", "community"],
  "Lutheran Campus Ministry": ["religion", "students", "faith"],
  "Machine Learning and Data Science": ["technology", "students", "machine learning"],
  "Management Information Systems Association": ["business", "students", "technology"],
  "Marine Science Institute Graduate Student Association": ["science", "students", "marine"],
  "Math Club": ["math", "students", "academic"],
  "Mathematics Graduate Representative Committee": ["math", "students", "academic"],
  "MBA Soccer Club": ["sports", "students", "soccer"],
  "Mechanical Engineering Graduate Student Board": ["engineering", "students", "mechanical"],
  "MEDLIFE at The University of Texas at Austin": ["healthcare", "students", "volunteering"],
  "MEDSIM": ["medicine", "students", "simulation"],
  "Mending Medical Minds": ["healthcare", "students", "volunteering"],
  "Mens Basketball Club": ["sports", "students", "basketball"],
  "Mental Health Agency of Student Government": ["health", "students", "mental health"],
  "Meow Mates": ["animals", "students", "pets"],
  "Michael T. Woodward Special Warfare Club": ["military", "students", "special forces"],
  "Minority Women Pursuing Law": ["women", "students", "law"],
  "Miracle Messages Austin": ["volunteering", "students", "outreach"],
  "Moody College Honors Student Council": ["students", "honors", "leadership"],
  "Moore-Hill Residence Hall Council": ["students", "housing", "community"],
  "Mosaic Minds University Initiative": ["mental health", "students", "awareness"],
  "Mosaic Texas": ["diversity", "students", "inclusion"],
  "MTNA - UT Austin": ["music", "students", "performance"],
  "Mu Delta Alpha @UT Austin": ["fraternity", "students", "leadership"],
  "Mu Epsilon Theta Sorority": ["sorority", "students", "community"],
  "Mu Rho Chapter of Phi Beta Sigma Fraternity Incorporated": ["fraternity", "students", "diversity"],
  "Mu Sigma Lambda": ["fraternity", "students", "leadership"],
  "Music Appreciation and Production Organization": ["music", "students", "production"],
  "Music United": ["music", "students", "unity"],
  "Muslim Legal Society": ["law", "students", "religion"],
  "Muslim Mental Health Organization": ["mental health", "students", "wellness"],
  "Muslim Students' Association": ["religion", "students", "community"],
  "Myanmar Student Association": ["culture", "students", "community"],
  "National Alliance on Mental Illness (NAMI) On Campus at University of Texas at Austin": ["mental health", "students", "advocacy"],
  "National Community Oncology Dispensing Association at the University of Texas": ["healthcare", "students", "oncology"],
  "National Community Pharmacists Association": ["healthcare", "students", "pharmacy"],
  "National Pan-Hellenic Council": ["fraternity", "students", "diversity"],
  "National Residence Hall Honorary": ["students", "leadership", "housing"],
  "National Society of Black Engineers": ["engineering", "students", "diversity"],
  "National Student Speech, Language and Hearing Association": ["healthcare", "students", "speech"],
  "Native American and Indigenous Peoples Association": ["culture", "students", "indigenous"],
  "Natural Sciences Council": ["science", "students", "academic"],
  "Nepali Student Association- Longhorn Chapter": ["culture", "students", "community"],
  "Net Impact (Graduate)": ["business", "students", "social impact"],
  "Neuroscience Graduate Students' Association": ["science", "students", "neuroscience"],
  "New Black Student Weekend": ["students", "culture", "community"],
  "New City College Ministry": ["religion", "students", "faith"],
  "New Student Services": ["students", "orientation", "support"],
  "New Wave Longhorns": ["students", "diversity", "community"],
  "New Works Student Council": ["students", "leadership", "performance"],
  "NexUs": ["students", "networking", "leadership"],
  "Normandy Scholars Program": ["students", "leadership", "community"],
  "Not On My Campus, UT Chapter": ["advocacy", "students", "activism"],
  "Noteworthy A Cappella": ["music", "students", "performance"],
  "Nritya Sangam Indian Dance Troupe": ["dance", "students", "culture"],
  "Nurses Christian Fellowship - UT Austin": ["healthcare", "students", "faith"],
  "Occupy Campus Ministry at the University of Texas at Austin": ["religion", "students", "faith"],
  "Office of Admissions": ["students", "admissions", "support"],
  "Office of the Dean of Students": ["students", "support", "leadership"],
  "Omega Chi Epsilon - Chemical Engineering": ["engineering", "students", "chemical"],
  "Omega Delta Phi Fraternity, Inc.": ["fraternity", "students", "community"],
  "Omega Psi Phi Fraternity Incorporated": ["fraternity", "students", "diversity"],
  "On the Moov": ["fitness", "students", "movement"],
  "One Health Student Association": ["healthcare", "students", "global health"],
  "OneWay South Asian InterVarsity": ["religion", "students", "community"],
  "Opportunities for Undergraduate Research at UT Austin": ["students", "research", "academic"],
  "Opportunities for Undergraduate Research at UT Austin Student Mentors": ["students", "research", "mentorship"],
  "Orange Bike Project": ["sustainability", "students", "biking"],
  "Origami Circle": ["creativity", "students", "arts"],
  "Orthodox Christian Campus Ministries at UT Austin": ["religion", "students", "faith"],
  "Orthodox Christian Fellowship of the University of Texas at Austin": ["religion", "students", "faith"],
  "Out of State, International, Transfer Student Agency of Student Government": ["students", "support", "community"],
  "OUTLaw - LGBTQ Law Student Association": ["law", "students", "LGBTQ"],
  "OUTreach at the University of Texas": ["LGBTQ", "students", "community"],
  "Partners in Health Engage at UT Austin": ["healthcare", "students", "volunteering"],
  "Party on the Plaza": ["students", "events", "social"],
  "Peace of Mind Foundation": ["mental health", "students", "wellness"],
  "Pediatric Pharmacy Association": ["healthcare", "students", "pharmacy"],
  "Peer Assistance and Leadership Students": ["students", "leadership", "mentorship"],
  "Persian Student Society": ["culture", "students", "community"],
  "Pharmacology and Toxicology Social and Outreach Committee": ["healthcare", "students", "pharmacy"],
  "Pharmacy Council": ["healthcare", "students", "pharmacy"],
  "Pharmacy Graduate Students Association": ["healthcare", "students", "pharmacy"],
  "Phi Chi Theta": ["business", "students", "leadership"],
  "Phi Delta Chi": ["fraternity", "students", "pharmacy"],
  "Phi Gamma Delta Fraternity": ["fraternity", "students", "community"],
  "Phi Kappa Psi Fraternity": ["fraternity", "students", "community"],
  "Social Anime Club": ["anime", "students", "community"],
"Social Entrepreneurship Learning Lab Fellowship": ["entrepreneurship", "students", "business"],
"Society for Advancement of Chicano/Hispanics and Native Americans in Science": ["science", "diversity", "students"],
"Society for Advancing Gender Equity in STEM": ["STEM", "gender equity", "students"],
"Society for Underwater Technology at the University of Texas at Austin Student Chapter": ["engineering", "technology", "students"],
"Society of Asian Scientists and Engineers": ["STEM", "students", "Asian American"],
"Society of Engineering and Architecture Students": ["engineering", "architecture", "students"],
"Society of Hispanic Professional Engineers": ["engineering", "Hispanic", "students"],
"Society of Petroleum Engineers": ["engineering", "students", "petroleum"],
"Society of Physics Students": ["physics", "students", "STEM"],
"Society of Women Engineers": ["engineering", "women", "students"],
"Socks for the Sole": ["community", "charity", "students"],
"Sorority and Fraternity Life": ["Greek life", "students", "community"],
"Space Law and Policy Society at The University of Texas at Austin": ["law", "space", "students"],
"Spanish Conversation & Culture Club at the University of Texas": ["language", "culture", "students"],
"SPIC MACAY Chapter at UT Austin": ["culture", "Indian", "students"],
"Sports Club at The LBJ School": ["sports", "students", "policy"],
"STEEL Dance Company": ["dance", "students", "performance"],
"Structural Engineering Association of Texas - Student Chapter": ["engineering", "students", "construction"],
"Student Academy of Audiology chapter at The University of Texas at Austin": ["audiology", "students", "healthcare"],
"Student Activities": ["activities", "students", "community"],
"Student Animal Legal Defense Fund at the University of Texas at Law School": ["law", "animals", "students"],
"Student Bar Association": ["law", "students", "leadership"],
"Student Chapter of the Society of Petrophysicists and Well Log Analysts at The University of Texas at Austin": ["engineering", "students", "geology"],
"Student Coalition for Caste Abolition": ["social justice", "students", "activism"],
"Student College of Clinical Pharmacy at The University of Texas at Austin": ["pharmacy", "students", "healthcare"],
"Student Conduct and Academic Integrity": ["academics", "students", "ethics"],
"Student Emergency Services": ["emergency", "students", "support"],
"Student Employee Excellence Development Program": ["employment", "students", "development"],
"Student Engineering Council": ["engineering", "students", "leadership"],
"Student Engineers Educating Kids": ["engineering", "education", "students"],
"Student Governance Organizations": ["student government", "leadership", "students"],
"Student Government": ["student government", "leadership", "students"],
"Student Health Advisory Committee": ["health", "students", "well-being"],
"Student Industry Pharmacists Organization": ["pharmacy", "students", "industry"],
"Student Mobilization": ["activism", "students", "community"],
"Student National Pharmaceutical Association": ["pharmacy", "students", "advocacy"],
"Student Veteran Center": ["veterans", "students", "support"],
"Students Demand Action": ["activism", "students", "gun control"],
"Students Expanding Austin Literacy": ["literacy", "students", "community"],
"Students Fighting Climate Change": ["environment", "activism", "students"],
"Students for a Cure": ["charity", "health", "students"],
"Students in Medical Laboratory Science": ["healthcare", "students", "laboratory"],
"Students Making Impacts Through Love & Empathy": ["community", "charity", "students"],
"Students of Caribbean Ancestry": ["Caribbean", "culture", "students"],
"StudentsCare at University of Texas at Austin": ["volunteering", "students", "healthcare"],
"Studio Art Graduate Association": ["art", "students", "graduate"],
"Study Abroad": ["travel", "students", "education"],
"Substance Abuse and the College Student": ["health", "students", "education"],
"Supply Chain Management Student Organization": ["business", "students", "supply chain"],
"Surviving SCA at The University of Texas at Austin": ["student support", "students", "mental health"],
"Sustainability Investment Group": ["sustainability", "investment", "students"],
"Sustainable Building Initiative": ["sustainability", "engineering", "students"],
"Swear2Care at UT": ["mental health", "students", "support"],
"Switch Energy Club Longhorn Chapter": ["energy", "students", "sustainability"],
"Synapse": ["neuroscience", "students", "research"],
"Table Tennis Club": ["sports", "students", "recreation"],
"TableTalk": ["debate", "students", "communication"],
"Taiwanese American Students Association": ["culture", "students", "Taiwanese"],
"Taiwanese International Student Association": ["culture", "students", "Taiwanese"],
"TAMID Group at UT": ["business", "students", "consulting"],
"Tau Beta Pi - Engineering": ["engineering", "honor society", "students"],
"Tau Beta Sigma - Beta Gamma Chapter": ["music", "students", "honor society"],
"Tau Kappa Epsilon Fraternity": ["Greek life", "students", "brotherhood"],
"Tau Sigma at The University of Texas at Austin": ["honor society", "students", "academics"],
"TCA Chinese Campus Fellowship": ["religion", "students", "Chinese"],
"Teachers of Tomorrow": ["education", "students", "teaching"],
"Teaching Refugees to Understand English at UT Austin": ["education", "refugees", "students"],
"Tech Consulting Group at The University of Texas at Austin": ["consulting", "students", "technology"],
"Technicbox": ["technology", "students", "innovation"],
"TEDxUTAustin": ["public speaking", "students", "events"],
"Terry Scholar Student Association": ["scholarships", "students", "leadership"],
"Test Org": ["organization", "students", "testing"],
"Texas 180 Degrees Consulting": ["consulting", "students", "business"],
"Texas 4000 for Cancer": ["charity", "healthcare", "students"],
"Texas Advertising Group": ["advertising", "students", "business"],
"Texas Aerial Robotics": ["engineering", "robotics", "students"],
"Texas Ahlul Bayt Student Organization": ["religion", "students", "Islamic"],
"TEXAS AMAL": ["religion", "students", "Muslim"],
"Texas Angels": ["charity", "students", "community"],
"Texas Argentine Tango": ["dance", "students", "Argentinian"],
"Texas Army ROTC": ["military", "students", "leadership"],
"Texas Asian Pacific American Medical Student Association": ["healthcare", "students", "Asian American"],
"Texas Asian Pan-Hellenic Council": ["culture", "students", "Asian American"],
"Texas Association of Black Journalists": ["journalism", "students", "diversity"],
"Texas Athletics": ["sports", "students", "athletics"],
"Texas Ballet Club": ["dance", "students", "ballet"],
"Texas Ballroom": ["dance", "students", "ballroom"],
"Texas Baseball Diamonds": ["sports", "students", "baseball"],
"Texas Beach Volleyball Club": ["sports", "students", "volleyball"],
"Texas Big Dippers": ["sports", "students", "recreation"],
"Texas Black Lens": ["film", "students", "diversity"],
"Texas Blazers": ["leadership", "students", "service"],
"Texas Convergent": ["technology", "students", "innovation"],
"Texas Council for Global Health Scholars": ["health", "students", "global"],
"Texas Cowboys": ["tradition", "students", "community"],
"Texas Creative Union Project": ["creativity", "students", "art"],
"Texas Crew": ["sports", "students", "rowing"],
"Texas Cricket Club": ["sports", "students", "cricket"],
"Texas Darlins": ["dance", "students", "performance"],
"Texas Dawah Team": ["religion", "students", "Muslim"],
"Texas Deewani": ["culture", "students", "Indian"],
"Texas Design, Build, Fly": ["engineering", "students", "aerospace"],
"Texas Dhoom": ["dance", "students", "Indian"],
"Texas Diabolo Association": ["sports", "students", "recreation"],
"Texas Dinosaur Club": ["science", "students", "paleontology"],
"Texas Disc Golf": ["sports", "students", "recreation"],
"Texas DnD": ["gaming", "students", "fantasy"],
"Texas Dollar For": ["charity", "students", "community"],
"Texas Dragon/Lion Dance Team": ["culture", "students", "performance"],
"Texas Economics Association": ["economics", "students", "business"],
"Texas embrACE": ["advocacy", "students", "support"],
"Texas Enactus": ["entrepreneurship", "students", "community"],
"Texas Energy Capital": ["energy", "students", "business"],
"Texas Energy Consulting": ["energy", "students", "consulting"],
"Texas Engineering World Health": ["engineering", "students", "health"],
"Texas Environmental Law Journal": ["law", "students", "environment"],
"Texas Equestrian Team": ["sports", "students", "equestrian"],
"Texas Equity Group": ["business", "students", "finance"],
"Texas Fashion for Students": ["fashion", "students", "community"],
"Texas Federalist Society": ["law", "students", "politics"],
"Texas Field Hockey": ["sports", "students", "field hockey"],
"Texas Finance Team": ["business", "students", "finance"],
"Texas Financial Derivatives": ["finance", "students", "derivatives"],
"Texas Fly Fishing": ["sports", "students", "outdoor recreation"],
"Texas Folklorico Dance Company": ["dance", "students", "culture"],
"Texas for Tots": ["charity", "students", "children"],
"Texas Fuego": ["dance", "students", "Latin"],
"Texas Future Leaders in Healthcare Administration": ["healthcare", "students", "leadership"],
"Texas Gearjammers": ["sports", "students", "motorcycling"],
"Texas Global": ["global", "students", "community"],
"Texas Gospel Fellowship": ["religion", "students", "Christianity"],
"Texas Guadaloop": ["dance", "students", "Latin"],
"Texas Gymnastics": ["sports", "students", "gymnastics"],
"Texas Handball": ["sports", "students", "handball"],
"Texas Health Promotion Club": ["health", "students", "wellness"],
"Texas Healthy Habits": ["health", "students", "fitness"],
"Texas Helping Hand": ["charity", "students", "volunteering"],
"Texas herScript": ["technology", "students", "women"],
"Texas Hillel": ["religion", "students", "Jewish"],
"Texas Hispanic Journal of Law and Policy": ["law", "students", "Hispanic"],
"Texas Hybrid Athlete Club": ["fitness", "students", "sports"],
"Texas Ice Hockey": ["sports", "students", "ice hockey"],
"Texas Immersive Institute": ["technology", "students", "VR/AR"],
"Texas Infinites": ["sports", "students", "dance"],
"Texas Institute for Discovery Education in Science": ["science", "students", "education"],
"Texas Intellectual Property Law Journal": ["law", "students", "intellectual property"],
"Texas Interdisciplinary Plan Community Outreach Organization": ["community", "students", "outreach"],
"Texas Interdisciplinary Plan Mentor Academy": ["mentorship", "students", "education"],
"Texas International Law Journal": ["law", "students", "international"],
"Texas Iron Spikes": ["honor society", "students", "engineering"],
"Texas Journal of International Affairs": ["international relations", "students", "journalism"],
"Texas Journal of Oil, Gas, and Energy Law Society": ["law", "students", "energy"],
"Texas Journal on Civil Liberties & Civil Rights": ["law", "students", "civil rights"],
"Texas Judo": ["sports", "students", "judo"],
"Texas Juggling Society": ["sports", "students", "juggling"],
"Texas Lassos": ["Greek life", "students", "community"],
"Texas Latin Dance": ["dance", "students", "Latin"],
"Texas Latinos in Engineering and Sciences": ["STEM", "Latino", "students"],
"Texas Law Disability and Neurodivergent Alliance": ["law", "students", "disability"],
"Texas Law Federal Bar Association": ["law", "students", "federal"],
"Texas Law Fellowships": ["law", "students", "fellowships"],
"Texas Law Review": ["law", "students", "publications"],
"Texas Law Sports & Entertainment Society": ["law", "students", "sports"],
"Texas Leadership Education and Development": ["leadership", "students", "development"],
"Texas Lean In": ["women", "students", "leadership"],
"Texas Lonestars": ["sports", "students", "cheerleading"],
"Texas Longhorn Yiddish": ["culture", "students", "Jewish"],
"Texas Luminescence": ["arts", "students", "performance"],
"Texas Mahjong Club": ["gaming", "students", "recreation"],
"Texas Materials Research Society": ["engineering", "students", "materials science"],
"Texas Materials Scientists and Engineers": ["engineering", "students", "materials science"],
"Texas Society of Professional Engineers at the University of Texas at Austin": ["engineering", "students", "professional"],
"Texas Society Of Unconventional Drummers": ["music", "students", "performance"],
"Texas Songbirds": ["music", "students", "singing"],
"Texas Spirits": ["dance", "students", "performance"],
"Texas Sport Management Club": ["sports", "students", "management"],
"Texas Sports Analytics Group": ["sports", "students", "analytics"],
"Texas State Employees Union": ["advocacy", "students", "labor"],
"Texas Stock Team": ["business", "students", "finance"],
"Texas Student Media": ["media", "students", "journalism"],
"Texas Student Psychological Association": ["psychology", "students", "mental health"],
"Texas Student Television": ["media", "students", "broadcasting"],
"Texas Student Tenants' Union": ["advocacy", "students", "housing"],
"Texas Success for Austin Youth Organization": ["charity", "students", "community"],
"Texas Sunshines": ["sports", "students", "cheerleading"],
"Texas Swedish Club": ["culture", "students", "Swedish"],
"Texas Sweethearts": ["Greek life", "students", "community"],
"Texas Swifties": ["music", "students", "fan club"],
"Texas Table Top": ["gaming", "students", "tabletop games"],
"Texas Taekwondo": ["sports", "students", "martial arts"],
"Texas Tai Chi": ["fitness", "students", "mindfulness"],
"Texas Taraana": ["dance", "students", "Indian"],
"Texas Theme Park Engineering and Design": ["engineering", "students", "design"],
"Texas THON": ["charity", "students", "philanthropy"],
"Texas Trap and Skeet": ["sports", "students", "shooting"],
"Texas Triathlon & Cycling": ["sports", "students", "triathlon"],
"Texas Undergraduate Consulting Group": ["business", "students", "consulting"],
"Texas Undergraduate Investment Team": ["business", "students", "investment"],
"Texas Undergraduate Law Journal": ["law", "students", "publications"],
"Texas Undergraduate Moot Court Team": ["law", "students", "debate"],
"Texas Undergraduate Research Journal": ["research", "students", "publications"],
"Texas Undergraduate Sales Organization": ["business", "students", "sales"],
"Texas UNICEF": ["charity", "students", "global"],
"Texas Veritas Forum": ["religion", "students", "faith"],
"Texas Visual Arts Collective": ["art", "students", "visual arts"],
"Texas Wesley UMCM": ["religion", "students", "community"],
"Texas Women in Economics": ["economics", "students", "women"],
"Texas Women's Club Lacrosse": ["sports", "students", "lacrosse"],
"Texas Women's Rugby": ["sports", "students", "rugby"],
"Texas Wranglers": ["Greek life", "students", "community"],
"Texas Writing Society": ["writing", "students", "literature"],
"Texas Wushu": ["sports", "students", "martial arts"],
"TexasHealthAI": ["technology", "students", "healthcare"],
"Thai Association of Austin": ["culture", "students", "Thai"],
"Thai Lao Cambodian Student Association": ["culture", "students", "Southeast Asian"],
"The Alzheimer's and Dementia Organization at The University of Texas at Austin": ["health", "students", "advocacy"],
"The American Constitution Society": ["law", "students", "politics"],
"The Annette Strauss Institute For Civic Life": ["civic engagement", "students", "leadership"],
"The Association of Black Psychologists": ["psychology", "students", "diversity"],
"The ATX Review at The University of Texas": ["writing", "students", "publications"],
"The Austin Meal Movement": ["charity", "students", "community"],
"The Center for Students in Recovery": ["health", "students", "recovery"],
"The Chi Phi Fraternity": ["Greek life", "students", "community"],
"The Community Engagement Collective": ["community", "students", "volunteering"],
"The Corral": ["Greek life", "students", "community"],
"The Dell Medical School Student Senate": ["healthcare", "students", "leadership"],
"The E. Lee Walker Fellowship at Texas": ["academics", "students", "fellowships"],
"The Fiber Arts Collective": ["arts", "students", "crafts"],
"The Fruits": ["charity", "students", "community"],
"The Greek Economics and Business Association": ["business", "students", "Greek life"],
"The Healthcare Equity, Advocacy, and Leadership Initiative": ["healthcare", "students", "advocacy"],
"The HOPE Initiative": ["charity", "students", "philanthropy"],
"The Imprimatur": ["publications", "students", "journalism"],
"The International Association of Business Communicators Chapter at the University of Texas at Austin": ["business", "students", "communications"],
"The L.O.V.E. Club": ["advocacy", "students", "community"],
"The Last Reformers": ["advocacy", "students", "politics"],
"The Latino Pan-Hellenic Council": ["Greek life", "students", "Latino"],
"The Law Veterans Association at the University of Texas School of Law": ["law", "students", "veterans"],
"The Longhorn Design Lab": ["engineering", "students", "design"],
"The Longhorn Rocketry Association": ["engineering", "students", "aerospace"],
"The Medical Device Student Forum": ["healthcare", "students", "medical devices"],
"The National Association of Black Accountants at The University of Texas at Austin": ["business", "students", "Black"],
"University Orchestra Student Association": ["music", "students", "performance"],
"University Panhellenic Council": ["students", "community", "sorority"],
"UNIVERSITY POLICE ORGANIZATION": ["security", "students", "community"],
"University Post-Production Association": ["media", "students", "production"],
"University Residence Hall Association": ["students", "housing", "community"],
"University Securities Investment Team": ["business", "students", "investment"],
"University Theatre Guild": ["theatre", "students", "performance"],
"University Unions": ["students", "community", "organization"],
"University Watch Association": ["security", "students", "community"],
"University Yoga Club": ["fitness", "students", "wellness"],
"UT Archery": ["sports", "students", "archery"],
"UT Badminton Club": ["sports", "students", "badminton"],
"UT Chapter Omicron Delta Epsilon- Economics Honor Society": ["honors", "students", "economics"],
"UT Dance Team": ["dance", "students", "performance"],
"UT Fencing Club": ["sports", "students", "fencing"],
"UT General Interest": ["students", "diversity", "interest"],
"UT ITF Taekwondo Team": ["sports", "students", "taekwondo"],
"UT Men's Soccer Team": ["sports", "students", "soccer"],
"UT Men's Ultimate Club": ["sports", "students", "ultimate frisbee"],
"UT Quantum Collective": ["science", "students", "quantum computing"],
"UT Racquetball Club": ["sports", "students", "racquetball"],
"UT Sailing Team": ["sports", "students", "sailing"],
"UT STAFF TOASTMASTERS": ["professional", "students", "public speaking"],
"UT Student Organization Advisors": ["students", "mentorship", "organization"],
"UT Toastmasters Club for Students": ["professional", "students", "public speaking"],
"UT Ukes": ["music", "students", "ukulele"],
"UT Water Ski Team": ["sports", "students", "water sports"],
"UT Women's and Non-Binary Ultimate Frisbee": ["sports", "students", "ultimate frisbee"],
"UT Women's Club Soccer": ["sports", "students", "soccer"],
"UT Women's Volleyball Club": ["sports", "students", "volleyball"],
"UT Women's Water Polo": ["sports", "students", "water polo"],
"UTalent Records": ["music", "students", "recording"],
"UTeach Liberal Arts Student Group": ["education", "students", "teaching"],
"UTeach-Liberal Arts": ["education", "students", "teaching"],
"UXPA at UT Austin": ["technology", "students", "UX design"],
"Valley Alliance of Mentors for Opportunities and Scholarships": ["mentorship", "students", "scholarships"],
"Vamos Tennis": ["sports", "students", "tennis"],
"Vector Student Engineering Magazine": ["engineering", "students", "media"],
"Veggie Lunch Club at The LBJ School": ["students", "community", "vegetarian"],
"Venture Capital Student Association": ["business", "students", "venture capital"],
"Vertical Flight Society at UT": ["engineering", "students", "aviation"],
"Veterinary Pharmacy Practice Association": ["healthcare", "students", "pharmacy"],
"Vietnamese Students Association": ["students", "community", "Vietnamese"],
"Voices of Afrika": ["music", "students", "culture"],
"Volunteerism and Service-Learning": ["service", "students", "volunteer"],
"Vow Ignite": ["entrepreneurship", "students", "community"],
"Wall Street Group": ["business", "students", "finance"]
  };